<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>ProxySettler</AssemblyName>
    <RootNamespace>ProxySettler</RootNamespace>
    <ApplicationVisualStyles>true</ApplicationVisualStyles>
    <ApplicationUseCompatibleTextRendering>false</ApplicationUseCompatibleTextRendering>
    <ApplicationHighDpiMode>SystemAware</ApplicationHighDpiMode>
    <InvariantGlobalization>true</InvariantGlobalization>
    <ApplicationIcon>Assets\ProxySettler.ico</ApplicationIcon>
  </PropertyGroup>

</Project>
